AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  ApiUrl:
    Description: Api Url
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/test
Resources:
  DynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: prefix
        AttributeType: S
      - AttributeName: priority
        AttributeType: N
      KeySchema:
      - AttributeName: prefix
        KeyType: HASH
      - AttributeName: priority
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: mock-api-responsemap
    Type: AWS::DynamoDB::Table
  Function:
    Properties:
      CodeUri: s3://ohgo/mock-api/1.0.0/5c2eb9545db05fd003cd447c3d2c4bbb
      Events:
        Api:
          Properties:
            Method: ANY
            Path: /{proxy+}
          Type: Api
      Handler: main.handle
      Role:
        Fn::GetAtt:
        - FunctionRole
        - Arn
      Runtime: python3.6
    Type: AWS::Serverless::Function
  FunctionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - dynamodb:*
            Effect: Allow
            Resource:
              Fn::GetAtt:
              - DynamoDBTable
              - Arn
          Version: '2012-10-17'
        PolicyName:
          Fn::Sub: ${DynamoDBTable}-FullAccess
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
